
name: Automate Release PR Creation

on:
  push:
    branches:
      - main

jobs:
  release-pr-creation:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(main): release')"
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN_ACTIONS }}
          release-type: node